GET https://travelbee-api-production.onrender.com/api/user/644930a753748334e8809519
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDQ5MzBhNzUzNzQ4MzM0ZTg4MDk1MTkiLCJyb2xlSWQiOjAsImlhdCI6MTY4NjAyNDQxOSwiZXhwIjoxNjkyMDcyNDE5fQ.JcDdQMrWZDOINQT-icCa0-cK1_2p_QVEwN8g3cbitNo