https://travelbee-api-production.onrender.com/api/groups/me/myGroups
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDQ4MTE1MzZjNDM0YzI5MDhkYTJlNmIiLCJyb2xlSWQiOjAsImlhdCI6MTY4NjUwNTkyMCwiZXhwIjoxNjkyNTUzOTIwfQ.tmvJlbiltDLlqecY6zDCyUsIRrS6z6GnjhopqIWALAo
####
https://travelbee-api-production.onrender.com/api/postsByGroupId/647dcf03eacbd44128198b7d
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDQ4MTE1MzZjNDM0YzI5MDhkYTJlNmIiLCJyb2xlSWQiOjAsImlhdCI6MTY4NjUwNTkyMCwiZXhwIjoxNjkyNTUzOTIwfQ.tmvJlbiltDLlqecY6zDCyUsIRrS6z6GnjhopqIWALAo